[package]
name = "beelog"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "beelog"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
toml = "0.8.23"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.40", features = ["derive"] }
ssh2 = "0.9.5"
