name: 构建 - Beelog

permissions:
  contents: write

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: x64
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            target: aarch64-unknown-linux-gnu
            runner: ubuntu-24.04-arm
          - os: osx
            arch: x64
            target: x86_64-apple-darwin
            runner: macos-13
          - os: osx
            arch: aarch64
            target: aarch64-apple-darwin
            runner: macos-latest
          - os: win
            arch: x64
            target: x86_64-pc-windows-msvc
            runner: windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: 切换目标代码
        uses: actions/checkout@v3

      - name: 设置Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: 添加Rust目标平台
        run: rustup target add ${{ matrix.target }}

      - name: 构建
        run: cargo build --release --target ${{ matrix.target }}

      - name: 准备二进制文件
        run: |
          BIN_NAME=beelog
          TARGET_DIR=target/${{ matrix.target }}/release
          OUT_DIR=beelog-${{ matrix.os }}-${{ matrix.arch }}/bin
          mkdir -p $OUT_DIR

          if [[ "${{ matrix.os }}" == "win" ]]; then
            cp "$TARGET_DIR/$BIN_NAME.exe" "$OUT_DIR/$BIN_NAME.exe"
          else
            cp "$TARGET_DIR/$BIN_NAME" "$OUT_DIR/$BIN_NAME"
          fi
        shell: bash

      - name: 压缩包
        run: |
          ZIP_NAME=beelog-${{ matrix.os }}-${{ matrix.arch }}.zip
          if [[ "${{ matrix.os }}" == "win" ]]; then
            powershell -Command "Compress-Archive -Path beelog-${{ matrix.os }}-${{ matrix.arch }} -DestinationPath $ZIP_NAME"
          else
            zip -r $ZIP_NAME beelog-${{ matrix.os }}-${{ matrix.arch }}
          fi
        shell: bash

      - name: 上传Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            beelog-${{ matrix.os }}-${{ matrix.arch }}.zip
